# logfilename                                                      [owner:group]  mode  count  size  when  flags
/Users/hllvc/Library/Logs/com.hllvc.tmux-autosave/main.log    hllvc:staff    644   5      512   *     GZ
/Users/hllvc/Library/Logs/com.hllvc.tmux-autosave/out.log     hllvc:staff    644   3      256   *     GZ
/Users/hllvc/Library/Logs/com.hllvc.tmux-autosave/err.log     hllvc:staff    644   3      256   *     GZ
