#!/bin/sh

GIT_FOLDER=arch-linux

cp /bin/update_pacman scripts
cd ~/.config
cp -r alacritty compton gtk-3.0 i3 polybar ranger zathura pulseaudio-ctl dconf gtk-2.0 htop pulse nvim  ~/github/$GIT_FOLDER/.config
cp betterlockscreenrc pavucontrol.ini user-dirs.dirs user-dirs.locale redshift.conf ~/github/$GIT_FOLDER/.config
cd ~
cp -r .gitconfig .local/share/fonts .fzf .oh-my-zsh ~/github/$GIT_FOLDER/home_rc_files
cp .extend.Xresources .gtkrc-2.0 .fehbg .vimrc .Xauthority .xinitrc .Xresources .zprofile .zsh* ~/github/$GIT_FOLDER/home_rc_files
