# logfilename                                                  [owner:group]  mode  count  size  when  flags
/Users/hllvc/Library/Logs/com.hllvc.tmux-warmup/main.log      hllvc:staff    644   5      512   *     GZ
/Users/hllvc/Library/Logs/com.hllvc.tmux-warmup/out.log       hllvc:staff    644   3      256   *     GZ
/Users/hllvc/Library/Logs/com.hllvc.tmux-warmup/err.log       hllvc:staff    644   3      256   *     GZ
