# logfilename                                                    [owner:group]  mode  count  size  when  flags
/Users/hllvc/Library/Logs/com.hllvc.homebrew-update/main.log   hllvc:staff    644   5      1024  *     GZ
/Users/hllvc/Library/Logs/com.hllvc.homebrew-update/out.log    hllvc:staff    644   3      512   *     GZ
/Users/hllvc/Library/Logs/com.hllvc.homebrew-update/err.log    hllvc:staff    644   3      512   *     GZ
