name: "🚀 [PROD](US) Deploy"

on:
  workflow_dispatch:
    inputs:
      image-tag:
        required: true
        type: string
        description: "Docker image tag to deploy"

permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  deploy-us:
    name: "Deploy US"
    uses: ./.github/workflows/_deploy_prod.yml
    with:
      aws-region: "us-east-2"
      image-tag: "${{ inputs.image-tag }}"
