# logfilename                                                     [owner:group]  mode  count  size  when  flags
/Users/hllvc/Library/Logs/com.hllvc.memory-pressure.log        hllvc:staff    644   5      1024  *     GZ
/Users/hllvc/Library/Logs/com.hllvc.memory-pressure.out.log    hllvc:staff    644   3      256   *     GZ
/Users/hllvc/Library/Logs/com.hllvc.memory-pressure.err.log    hllvc:staff    644   3      256   *     GZ
